#apiVersion: v1
#kind: Service
#metadata:
#  name: wordpress
#  labels:
#    app: wordpress
#spec:
#  ports:
#    - port: 80
#      targetPort: 32723
#      type: NodePort
#  selector:
#    app: wordpress
#    tier: frontend 

#create a service for wordpress
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
#      nodePort: 30000
  selector:
    app: wordpress
    tier: frontend
  type: NodePort

    
