# create a service for wordpress
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
#      nodePort: 30000
  selector:
    app: wordpress
    tier: frontend
  type: NodePort

#apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: MYSQL_DATABASE
          value: "wordpres"
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass          # generated before in secret.yml
              key: password
#        ports:
#        - containerPort: 80
#          name: wordpress
#        volumeMounts:
#        - name: wordpress-persistent-storage
#          mountPath: "/var/www/html"          # which data will be stored
#      volumes:
#      - name: wordpress-persistent-storage
#        persistentVolumeClaim:
#          claimName: myclaim
